server:
  port: 8888
  context-path: /youchuangxg

spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.1.100:3306/youchuang_xg
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
        database: 0
        host: 192.168.1.33
        port: 6379
        password: myycxgjava
        pool:
          max-active: -1
          max-wait: -1
          max-idle: 8
          min-idle: 0
        timeout: 0
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.winter.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

youchuangxg:
    filePath: D:\nginx-1.8.1\html\youchuangxgcer
    uploadfile: D:\nginx-1.8.1\html\youchuangxg
    DownloadUrl: http://192.168.1.208/publicStorePath/

sms:
    accessId: LTAIv3GbnduOlkA5
    accessKey: Uv5P5YUfZjtBAZ1Y6EhGdIpJfriedc
    signName: 烟品上滩率
    codeTemplate: SMS_149416604
    product: Dysmsapi
    domain: dysmsapi.aliyuncs.com